### ISSUE TITLE
Same line number printed next to each test in results table

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS-Tester-Module#11]
Bug visible in picture in this PR: https://github.com/daylightstudio/FUEL-CMS/pull/489

PHP 7.2.9

**Comment by martynassateika** [comment]
Looks like updating `\MY_Unit_test::_backtrace` fixed some of the tests I've tried:

```php
$index = (string) count($back) - 6; // {{{ FUEL Added to get proper line numbers}}}
```

Works if you replace the `6` there with a `5`.

Do we know what caused this?

I could set up a PR if you think it's safe to make the change @daylightstudio :-)

**Comment by daylightstudio** [comment]
Yes... please do.

**Comment by martynassateika** [comment]
I'll try to open one up tonight. Just want to understand what caused it to suddenly stop working at some point so I'll play around with the debugger a bit first.

**Comment by daylightstudio** [comment]
There may have been a change in function calling structure at one point that caused that backtrace index to change but am not sure (it's been a while).
