### ISSUE TITLE
No "develop" branch

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS-Tester-Module#3]
Could we have a 'develop' branch, just to follow the branching model of the main FUEL-CMS repository? I would like to contribute several fixes.

**Comment by martynassateika** [comment]
I cannot see it, though? :-/ This is for the FUEL-CMS-Tester-Module repository.

**Comment by daylightstudio** [comment]
Ahh... try now.

**Comment by martynassateika** [comment]
Yup, all good now. Thanks!
